spring:
  application:
    name: product-service

  output:
    ansi:
      enabled: always

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true

  h2:
    console:
      enabled: true

  datasource:
    url: jdbc:h2:file:~/product
    driver-class-name: org.h2.Driver

logging:
  level:
    com:
      shiro: debug
    org:
      hibernate:
        SQL: debug
        type:
          descriptior:
            sql:
              BasicBinder: trace
  pattern:
    console: "%clr(${LOG_LEVEL_PATTERN:%5p})  %m%n${LOG_EXCEPTION_CONVERSION_WORD:%wEx}"

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.intance_id:${random.value}}

server:
  port: ${PORT:0} # the application automatically assigns an available port